### ISSUE TITLE
Weird alignment on file includes

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#111]
The "download raw" link aligns a bit strangely with inline text:

![image](https://user-images.githubusercontent.com/7783288/29004914-ca08511c-7a9d-11e7-8c12-9bac6241b97d.png)

I'd prefer to have it so that the download raw text takes up a little less vertical space and the text does not wrap it. With text wrapping, it makes it look too much like it's a link in the text itself rather than attached to the code snippet.

**Comment by shredtechular** [comment]
@mtlynch I'm going to go with a solution that looks like this below snippet as I feel like this follows the current style and also solves the problems you identified in the issue:

<img width="1033" alt="screen shot 2017-08-12 at 12 45 37 pm" src="https://user-images.githubusercontent.com/2396774/29242497-72505186-7f5c-11e7-8a4a-9377bd44ed9a.png">

Does that look okay to you from a mockup perspective?

In order to try and make the download link more identifiable/attached to the code snippet, I was also thinking of one of these two options, in order of what I, personally, like best.  Would you rather go with something like one of the below two examples?  And you could move any of these styles to other corners of the code block too.  I was thinking something in the top left might save more on vertical spacing though.

---

### Example "download raw" mockup with link in upper right of code block
<img width="1038" alt="screen shot 2017-08-12 at 12 41 06 pm" src="https://user-images.githubusercontent.com/2396774/29242493-67c61098-7f5c-11e7-8ff2-5485f54084eb.png">

---

### Example "download raw" mockup with link in lower right styled like a tab to the code block
<img width="1031" alt="screen shot 2017-08-12 at 12 43 03 pm" src="https://user-images.githubusercontent.com/2396774/29242495-6e91c0ac-7f5c-11e7-9944-ca8e90065c6f.png">

**Comment by mtlynch** [comment]
The existing style is good, but I think the tab is even better. Can you give an estimate of how long that would take to implement?

**Comment by shredtechular** [comment]
I would say about an hour.  I know the styles that need to be applied and everything, but this is definitely something we will want to test out across some different browsers/widths/devices I think, so I think the majority of that time would be for that.  Certainly let me know if you would like me to switch to the tab style.

**Comment by mtlynch** [comment]
Yeah, that sounds good. Can we do the tab?

**Comment by shredtechular** [comment]
Absolutely!  I'll work on getting a PR together for that today.
