### ISSUE TITLE
Control thumbnails for sharing on Twitter and Reddit

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#147]
I'd like to know if there is any way of controlling the thumbnail picture that appears when I share mtlynch.io post on Twitter or Reddit. Reddit seems to just pick the first image it finds.

Twitter doesn't show an image at all, it just shows this:

![image](https://user-images.githubusercontent.com/7783288/30352401-aada926a-97ed-11e7-8836-34109502d9b9.png)

By contrast, posting an article from The Guardian (e.g. [this one](https://www.theguardian.com/commentisfree/2017/sep/09/mark-zuckerberg-president-facebook-algorithm)) looks like this:

![image](https://user-images.githubusercontent.com/7783288/30352380-944399ac-97ed-11e7-91df-59c0ade3ed95.png)

Is there a way of controlling the image that Reddit picks and making the link sharing look fancy like The Guardian?

**Comment by shredtechular** [comment]
When sharing links/blog articles on social media, the [Open Graph protocol](http://ogp.me/) is used which are basically just meta tags in the `<head>` tag of a page.  Unfortunately there is quite a lot of differences in how social media sites implement that protocol on their end which is why on Twitter you don't currently see an image at all, yet Reddit you see it picks the first image it finds as the default if one isn't supplied.

All that said, the the parent theme has implemented populating the Open Graph meta tags by using the following logic:
```
If header.image exists in the yml frontmatter for a page/post, use that for the image
Else if header.teaser exists in the yml frontmatter for a page/post, use that for the image
Else if og_image exists in the site's _config.yml file use that for the image
```

Currently the site's `og_image` is left blank in it's `_config.yml` file.  This could be used if you wanted a default image to fall back on or use for all posts.

And I don't see `header.image` or `teaser.image` frontmatter in any of the posts currently.  Adding an image into `header.image` probably isn't desired because that puts a hero image on your post which I don't think you have or want.

I did a simple test using `header.teaser.image` in my local environment on the `/sia-nextcloud` post setting it like so in the frontmatter:
```
header:
  teaser: images/2017-08-06-sia-nextcloud/nextcloud-complete.png
```
Below are the results of that on Twitter, so you can see the image showing in the tweet:
<kbd>
<img width="591" alt="screen shot 2017-09-14 at 10 35 38 pm" src="https://user-images.githubusercontent.com/2396774/30464793-9e9e6b6a-99a1-11e7-9ece-ceeaf67343fd.png">
</kbd>

That said, using the `header.teaser` frontmatter, has other effects on the local site.  As you can see in the below screen cap, using the `header.teaser` frontmatter key will also add the image to the top of related posts:
<kbd>
<img width="1032" alt="screen shot 2017-09-14 at 11 09 58 pm" src="https://user-images.githubusercontent.com/2396774/30464832-deee0cd4-99a1-11e7-8307-3ebd4d52d9fe.png">
</kbd>

So, I'm not sure if that is desirable to do from your perspective?  If that isn't desirable, then I think we should add our own frontmatter key standard to use for social media image sharing.  For example, we could create a `og_image` frontmatter key in all posts.  That way we know it won't alter the current site's look, yet it will enable the fancier image sharing on social media.  In order to get that to work, we would need to hack/customize the parent theme's head layout a bit, but I'm hopeful that can be accomplished in a not too intrusive way.

Hopefully I explained that in a somewhat coherent way?  If that still doesn't make sense or I can clarify any of that, please let me know!

**Comment by mtlynch** [comment]
Okay, awesome! That's super helpful. I like the way that it populates the images in the related posts, so `header.teaser` seems like the way to go. I just created PR #152 to add `header.teaser` to all the past posts.

**Comment by shredtechular** [comment]
That is awesome, that PR looks perfect!  Sorry for not finding the alt attribute issues, I didn't even think of that part!  I liked your solution there though, nice job!!

**Comment by mtlynch** [comment]
Oh yeah, no problem. I submitted a PR to try to get it upstream:

https://github.com/mmistakes/minimal-mistakes/pull/1255

**Comment by mtlynch** [comment]
Hmm, I'm still getting no image:

![image](https://user-images.githubusercontent.com/7783288/30515339-b1d43cac-9af3-11e7-9677-0118bcf87acc.png)

Even though I see this in the generated HTML:

```html
<meta property="og:image" content="https://mtlynch.io/images/resized/2017-06-27-greenpithumb/480/greenpithumb-side-full.jpg">
```

Any idea what's going wrong?

**Comment by mtlynch** [comment]
It might just be some kind of caching issue. It works for some of my posts, like the [homelab one](https://mtlynch.io/building-a-vm-homelab/). I'll reopen if it's still like this tomorrow

**Comment by shredtechular** [comment]
Yeah, I'm pretty sure it probably is a caching issue and it can take a bit to crawl.  Your example worked for me on Twitter:
<img width="583" alt="screen shot 2017-09-16 at 3 37 19 pm" src="https://user-images.githubusercontent.com/2396774/30515490-9bb20f0a-9af6-11e7-9b76-13d02a89aa94.png">


However, I think it may take some more time on Reddit...at least that's how its looking to me.  The open graph data looks correct to me.  I think it is a good idea to check this tomorrow to see.
