### ISSUE TITLE
Bad caption alignment on center-aligned figure images

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#167]
I noticed that when I use the following image include (in branch `cr1`):

```yaml
{% include image.html file="flowchart.jpg" alt="Code review flow" fig_caption="Placeholder chart, replace with illustration" max_width="600px" img_link=true %}
```

The caption appears to the right of the image, instead of below it:

![image](https://user-images.githubusercontent.com/7783288/31105802-a31cf4b0-a7b4-11e7-8a71-e539301a4b0a.png)

I'd like for the include to generate an image that's limited to 600px, centered, and has the figure caption directly below the image.

**Comment by mtlynch** [comment]
I just realized that omitting an `align-left`/`align-right` doesn't actually align it center. I'd like images to always be center aligned unless otherwise specified. Can you think of pitfalls to that?

**Comment by shredtechular** [comment]
@mtlynch we can default images and figures to be centered by default without a problem.  The only pitfall I can think of here is there are images that are currently defaulted to the left.  For example, on https://mtlynch.io/windows-sia-mining/, the images in the ordered lists are left aligned, so changing the default to center would result in those images being centered.  Is that okay or do you prefer those left-aligned?  If you would like those left aligned, we would probably either need to make a rule that all images in `<ol>` are left aligned or create a new css class for this behavior.  We can't simply use `class="align-left"` for this use case since it will float text around the image as you see on other pages.

## Ordered list images currently left-aligned:
<kbd>
<img width="1031" alt="screen shot 2017-10-08 at 10 47 58 am" src="https://user-images.githubusercontent.com/2396774/31317893-1482a4fe-ac17-11e7-8f73-7ad90c5c9449.png">
</kbd>

## Ordered list images with default center align:
<kbd>
<img width="1024" alt="screen shot 2017-10-08 at 10 47 47 am" src="https://user-images.githubusercontent.com/2396774/31317895-227a1bdc-ac17-11e7-9e4c-e74818fdd5e3.png">
</kbd>

## Other examples of current left align images that would change with default center change:
This is on the https://mtlynch.io/sia-via-docker/ page.

### Before
<kbd>
<img width="1064" alt="screen shot 2017-10-08 at 10 55 35 am" src="https://user-images.githubusercontent.com/2396774/31317912-6689d81c-ac17-11e7-9f78-df8d6218ee1b.png">
</kbd>

### After default change
<kbd>
<img width="1074" alt="screen shot 2017-10-08 at 10 55 53 am" src="https://user-images.githubusercontent.com/2396774/31317920-7ed2d0f4-ac17-11e7-8388-b0511a6887cb.png">
</kbd>

## Finally, new post images with default center change

<kbd>
<img width="872" alt="screen shot 2017-10-08 at 10 56 27 am" src="https://user-images.githubusercontent.com/2396774/31317930-9ae8fa5c-ac17-11e7-8f8f-26ec9a1625df.png">
</kbd>

<kbd>
<img width="781" alt="screen shot 2017-10-08 at 10 58 30 am" src="https://user-images.githubusercontent.com/2396774/31317937-b2f51dc4-ac17-11e7-9589-96df11a95b58.png">
</kbd>

**Comment by mtlynch** [comment]
Okay, cool. I think center alignment actually looks better in all of those cases.
