### ISSUE TITLE
Research: Support translations

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#203]
I've received a request to host a Portuguese translation of some of my articles (reader-contributed translations).

It looks like Jekyll can support multiple languages. Can you research what would be best here?

Assumptions:

* Only a small subset of posts will have translations
* Each post will probably only have 1-2 translation
* I'd prefer the English version to look the same as it is now. Maybe at the end of the article, include a link to available translations.

**Comment by shredtechular** [comment]
Jekyll can certainly support i18n for websites out of the box using proper structure and code.  There are also several plugins out there that can aid in the effort and simplify the coding/content effort.  I've also checked the parent theme and it also does incorporate some minimalistic translations (or placeholders at least) for some of the default text that the theme uses.  Below are some of my additional thoughts on the problem and possible solutions.

## Considerations for choosing a solution
- Should be flexible enough to accommodate multiple language translations
- Should be intuitive for end users and provide benefit for actually implementing a solution and maintaining translations
- Should be easy to add translations in a consistent manner for all posts/translations

## Questions on assumptions that could impact solutions/recommendations
- The original issue states "Only a small subset of posts will have translations" and "Each post will probably only have 1-2 translations".  Is that more from an initial starting perspective as it will take time for translations to be curated?  In other words, would there be a goal to eventually translate the entire site at some point?
-  The last assumption that states, "I'd prefer the English version to look the same as it is now. Maybe at the end of the article, include a link to available translations." coupled with "Each post will probably only have 1-2 translations" makes me think that if a user is on the `/editor` post that they would also have the option to choose another language if there were 1 or many translations in 1 or many other languages, right?  So, just as an example, if the `/editor` post had the first paragraph translated in Portuguese and the last paragraph had a translation in French, the user would be given an option to view Portuguese and French translations, right?  And if they chose Portuguese they would then be delivered the `/editor` post with the first paragraph translated in Portuguese but the remaining content in English?  Am I understanding that correctly?

## Possible Solutions

### Translate Entire Site for each language desired
I know this doesn't sound like it meets the original assumptions at all, and it probably doesn't!  I also understand that maybe translating the entire site to another language may not be easily accomplished, but I do feel it is at least important to bring into the discussion.

#### Implementation for full site translations
The implementation if you wanted to do a full site translation would follow many other sites out there such as healthcare.gov, cancer.gov where an end user could simply choose their language preference once and then move throughout the site in that specified language.  Basically it would translating all of the posts/pages into a subdirectory like `/pt` for Portuguese for example and then inserting a yml frontmatter key to tell Jekyll what language that page is in, i.e. - `lang: en` or `lang: pt`.  Then the layouts/includes would need to be fixed/tested to make sure that content/links/etc are `lang` aware.

#### Pros
- I believe this would provide a full i18n solution and I think would probably maximize the benefit for non-English speaking readers.
- I think there could be some significant SEO boosts with this solution
- I think technical LOE is low/medium for this option.

#### Cons
- Obvious concern is probably accumulating and plugging in all of the translations for all of the content.  I imagine that could be a huge blocker for this option.
- I also have some concerns that the parent theme may not fully support this type of implementation, however, I think it would not be terrible to fix those areas.  I think there are plugins out there that could also help with this type of implementation like 

### Javascript translations
If we are truly talking about a partial and very small subset of translations scoped to just blog post content, I think it might be nice to utilize JS here to dynamically show/hide translations on the current page as opposed to take the user to a distinct page that has MOST of the same content as another page.

#### Implementation for JS translations
To implement this solution, my thoughts would be to put the translations for posts/pages right into the markdown content either underneath or on top of the english content.  We could then assign a class within markdown to those translations and have CSS hide those translations on page load.  When a user selects the language translation of their choice, the translations could then replace or even appear in a highlighted box above or below the English content.

#### Pros
- From a content writer perspective, I think it might be easier to have *simple* and *few* translations all in the same markdown file.  This might be more of a personal preference, but thought it okay to add as a positive.  *NOTE* - However, the more languages there are and numerous the amount of translations, this could become unruly.
- A user doesn't have to navigate to a whole distinct page just to view a few translations?  Everything is populated right in place and no confusing navigational issues.
- Since Jekyll isn't building additional separate pages, this shouldn't negatively impact build times.

#### Cons
- There could be some UI issues if a user selects Portuguese translations on one post, then navigates to another post and may have to select Portuguese translations again for that page.  We might be able to use cookies/local storage to get around this, but then we are introducing other complexities that may not be desired.  And maybe selecting translations on each post isn't a big deal?
- I don't believe there would be as significant a boost in SEO compared to the first option.  Debatable compared to the third option.
- I also fear scalability complexities with this option if down the road, readers also wanted other languages, not just Portuguese.  That one, simple markdown file with all of the content in the same file just got a lot more unruly if down the road readers wanted French, Spanish, Italian, German, and Japanese translations too...

### Separate page for translations
The last option, which might sound complex, is to create a completely separate page for each given translated post.  So, for example, if there were translations for `/editor` the Portuguese translated post would be built to `/pt/editor` and the Spanish version fo the translated post would be built to `/es/editor`, etc.

#### Implementation for separate translation posts
The technical implementation could vary here, however, since we are only talking about a few translations per post, I was thinking we utilize includes here for common content between an English and Portuguese version of a post.  Then keeping the translated content in each post.

#### Pros
- I think this is more scalable than option #2 for additional future languages.
- I think this could be a more "organized" solution compared to #2 if we could figure out how to not duplicate the english content on both pages.

#### Cons
- I think there could be some confusing UI navigational issues for end users with this solution due to partial translations and going back and forth between English and partially translated pages.
- I think we could end up complicating the content writing process if we didn't want to duplicate non-translated content in the distinct markdown files.
- More pages to build which means _possibly_ and _conceivably_ we run into a slower build process...at some point...as more languages/translations are added.

**Comment by mtlynch** [comment]
>Is that more from an initial starting perspective as it will take time for translations to be curated? In other words, would there be a goal to eventually translate the entire site at some point?

Ah, good question. We'll probably never translate the entire site. It would just be best effort translations as people donate them. So `/human-code-reviews-1` might have translations in English, Spanish, and Japanese, but `/editor` might only be available in English. It's a safe assumption that less than 10% of the posts will ever be translated.

>So, just as an example, if the /editor post had the first paragraph translated in Portuguese and the last paragraph had a translation in French, the user would be given an option to view Portuguese and French translations, right? And if they chose Portuguese they would then be delivered the /editor post with the first paragraph translated in Portuguese but the remaining content in English? Am I understanding that correctly?

Oh, to clarify, we can assume translation is at the granularity of post+language. So we don't need to design for a situation where we have a Portuguese translation for paragraph 1, but not for paragraph 2. If a translation is available for `/editor`, it would be

**Comment by mtlynch** [comment]
Thanks for this research! I haven't heard back from the translator, so it doesn't seem like I'll be able to move forward on this, but it's good to know if the question comes up in the future.

But just for posterity if we unfreeze this:

* I'm leaning towards option 3. I like the ability to link directly to a translated version of a page (though I guess if we really wanted, we could do this with URL query parameters + JS). My next preference is option 2, but I'm not crazy about keeping all the different content in one big file.
* I'd also be interested in plugins that handle the work of this strategy for us so we don't end up reinventing the wheel.
