### ISSUE TITLE
Support for image.html include with 2-3 images

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#212]
The parent theme has support for [two up](https://mmistakes.github.io/minimal-mistakes/markup-more-images/#two-up) and [three up](https://mmistakes.github.io/minimal-mistakes/markup-more-images/#three-up) displays of images.

I'd like to have a way to use the blog's `{% include image.html %}` feature, but with support for two or three images so that they display two or three horizontally, with an optional caption, as in the parent theme's examples.

**Comment by shredtechular** [comment]
Got it, this is a good idea and item to point out.  We do currently have a "work around" way to use the two/three up image displays and are using that method in the [geenpithumb post](https://mtlynch.io/greenpithumb/#the-final-product).  In the markdown for that page for those side-by-side images you can see we have the following:

```
<figure class="half">
  {% include image.html file="greenpithumb-side-full.jpg" alt="GreenPiThumb full system" img_link="true" media_rendition="half" %}
  {% include image.html file="greenpithumb-front.jpg" alt="GreenPiThumb full system" img_link="true" media_rendition="half" %}
</figure>

<figure class="third">
  {% include image.html file="greenpithumb-just-electronics.jpg" alt="GreenPiThumb electronics" img_link="true" media_rendition="third" %}
  {% include image.html file="greenpithumb-pump.jpg" alt="GreenPiThumb pump" img_link="true" media_rendition="third" %}
  {% include image.html file="greenpithumb-reservoir.jpg" alt="GreenPiThumb reservoir" img_link="true" media_rendition="third" %}
</figure>
```

So, I'm not sure if that is a great solution for you or what you were looking for, but that is one way to accomplish the two/three up image display with the current codebase and responsive image plugin.  I'm also not 100% ideal that is a great coding solution in terms of mixing html with the liquid and markdown...but we do have other areas where we have similar coding behavior.  And maybe more importantly what would make the most sense and is easiest for you when creating the images in the markdown?  In other words, i think we can improve the current implementation by adding the capability to have arrays and multiple images within a figure tag, but what is most intuitive and easiest to implement?

Do you think any of these would be better (easier and more intuitive) than the current implementation?

### Option 1:
Double the parameters in the include and add an "_#" to the end of each parameter.  

#### Example implementation of Option 1:
```
{% include image.html file_1="greenpithumb-side-full.jpg" alt_1="GreenPitThumb full system" img_link_1="true" media_rendition_1="half" file_2="greenpithumb-pump.jpg" alt_2="GreenPiThumb pump" img_link_2="true" media_rendition_2="half" fig_caption="If you wanted a Figure Caption too" %}
```

#### Pros & Cons of Option 1:
The advantage is keeping all the configuration for the side-by-side images all in the include.  Disadvantage to me is it seems messy, unorganized, and seems has the potential to get unruly if the functionality ever went to 4, or, 5, or 6, images across like thumbnails...that would be one long "yucky" include!

### Option 2:
Use arrays for the parameter values

#### Example implementation of Option 2:
Probably many ways to do this and would want to experiment a little, but what I have in mind is something like:
```
{% assign images = "greenpithumb-side-full.jpg,greenpithumb-pump.jpg" %}
{% assign alts = "GreenPitThumb full system,GreenPiThumb pump" %}
{% include image.html file=images alt=alts img_link="true" media_rendition="half" fig_caption="If you wanted a Figure Caption too" %}
```

#### Pros & Cons of Option 2:
To me the advantage is organization and readability.  It is easier to work/read arrays than 25 different variables, right?  The disadvantage is maybe not as easy and could cause frustration setting liquid variables in markdown?  Could also use yml arrays/objects instead of liquid variables, but still seems like it requires more technical know-how than it should?  And wonder if this is easier than simply adding the HTML directly in?  Do you like this option and is it intuitive to the way you work and think?  Would you rather do that or work with the HTML directly that you can use in the current implementation above?

Happy to work on either of those options and I think Option 2 would probably be the better way to do it in my personal preference!  But it's up to you and want to make sure you get value out of that time/work.  Or if you have any other better/different ideas of how you would ideally add multiple side-by-side images?  For example, if you were adding 2/3 up images what ideally would you like to type in to your post for it to render/display properly?

**Comment by mtlynch** [comment]
Oh! I forgot we already solved it in the GreenPiThumb post. That's actually my favorite in terms of what the code looks like.

I agree it's risky to depend on possibly-not-defined behavior by mixing HTML and CSS, but it's a feature I use infrequently that it might be okay to just risk it and fix it if we break in a later version of Jekyll or Minimal Mistakes.

I'm going to use that for now.

The below is just for future reference in case we have to revisit this.

Option 1, I agree with you that the naming is awkward. Would it be possible to have it so that the existing semantics work, but the `_#` semantics work as well? Basically, I'd want it to be that these two lines are equivalent:

```
{% include image.html file="foo.jpg"
...
{% include image.html file_1="foo.jpg"
```

I'd want to use the `file` name for the common case and the `file_1` name for the case of multiple images. Would that be possible?

```
{% include image.html file_1="greenpithumb-side-full.jpg" alt_1="GreenPitThumb full system" img_link_1="true" media_rendition_1="half" file_2="greenpithumb-pump.jpg" alt_2="GreenPiThumb pump" img_link_2="true" media_rendition_2="half" fig_caption="If you wanted a Figure Caption too" %}
```

Option 2, I'm too irked by having to keep arrays in sync. Like I feel like it would be too confusing to keep it `images="A,B,C"`, alts="A,B,C"`.

Is it possible to somehow define a variable that captures each image's information and then we join them together in the include?

I'm imagining something like this (I'm totally making up the syntax):

```
{% assign image_1 = "{ 'file': 'first-image.jpg', 'alt': 'first alt' }" %}
{% assign image_2 = "{ 'file': 'second-image.jpg', 'alt': 'secont alt' }" %}
{% include image.html file=images images="[image_1,image_2]" img_link="true" fig_caption="Group caption" %}
```

**Comment by shredtechular** [comment]
OK, that sounds good, totally understand!  To answer your questions:

> I'd want to use the file name for the common case and the file_1 name for the case of multiple images. Would that be possible?

Yes, I'm 99% sure that would be possible.  It might make some of the code in the include a bit messy, but pretty sure that is doable.

> Is it possible to somehow define a variable that captures each image's information and then we join them together in the include?

Hmm, that is interesting and I see what you are doing there looking at the syntax.  I feel like doing that kind of thing in liquid templating is not going to be easy since it doesn't natively support arrays/objects without doing some hacky-ish things.  That said, I can definitely see using YML to do this sort of thing.  So, we could do something like this syntax in the post's YML frontmatter (or even in a separate data file if you prefer...):
```
two-up-imgs:
  - file: first-image.jpg
     alt: "first alt"
  - file: second-image.jpg
     alt: "second alt"
```
Then, the include would look something like:
```
{% include image.html file=post.two-up-imgs img_link="true" fig_caption="Group caption" %}
```
So, I definitley like the "clean-ness" factor of doing it like this!  But just not sure how easy it is to author by scrolling up the page to the frontmatter and aligning yml key names to where you want the image includes, etc?  But that option is DEFINITELY something to think about I think!

Finally, I was giving it a little more thought over night and instead of creating `{% assign %}` liquid variables or formatting yml keys in the example above (if you don't like that...) is we could also just simply send in a "string" for the names/alt tags and split it out in the template.  So, something like below:
```
{% include image.html file="first-image.jpg,second-image.jpg" alt="first alt,second alt"  img_link="true" fig_caption="Group caption" %}
```

So if you think that might be easier we could do that too...  So many options I guess! Ha!  Just whatever you think might be easiest on you when creating the posts...

**Comment by mtlynch** [comment]
Oh that last comma-separated option is pretty good. It has the downside of keeping arrays in sync, but it's pretty trim.

I'll stick with the mixed Liquid + HTML for now, but we'll reopen if this breaks us in the future.
