### ISSUE TITLE
Research: End-to-end functional tests

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#218]
What are some functional tests we can integrate into the site? I'm interested in functional tests of these features:

* testing hover anchor links are working
* testing image pop-ups are working
* testing mobile menu working

Goal of the research is to determine:

* Estimated time-cost
* Technology/strategy for testing

**Comment by mtlynch** [comment]
I just did some e2e tests for another project. A lot of it could probably be repurposed for the blog:

https://github.com/mtlynch/isitketo_webapp/blob/master/build#L29-L38
https://github.com/mtlynch/isitketo_webapp/tree/master/e2e

It spins up selenium servers, then runs an [e2e script](https://github.com/mtlynch/isitketo_webapp/blob/master/e2e/e2e.py) to load the homepage, perform searches, and verify expected elements are in the result pages. It repeats the test for Firefox and Chrome.

**Comment by shredtechular** [comment]
So, it sounds like the ask for e2e tests is really the ability to simulate what actions an end user may perform on the website.  The major hurdle in getting some automated tests in place to do this is creating an automated testing framework within the site.  Once we decide on the testing framework and have it in place, my hope is it would be pretty easy to continually add more and more tests to cover the critical/major components of the site.

So, after doing some research and reviewing the information provided on your other projects, I see a couple of different options for the testing framework:

## Option 1 - Docker/Selenium setup
This is certainly an option and I'm sure we can figure out how to implement something similar into the Jekyll site.  I won't go into too many details here as I'm sure you know more about this option than I do, but from my perspective I'll detail some pros/cons/LOE below:

### Pros
- As previously stated, owner familiarity with these technologies and similar implementation methods
- (I think?) This method **_could_** be more efficient in terms of actually running the tests?  That is if there were a significant number of tests, which I'm not sure we'd have for the blog?

### Cons
- From my perspective this is a more complex implementation and not sure it fits into Jekyll as nicely.
- The way I see it, If ruby unit tests were ever needed, you'd need a separate and distinct testing framework for that as well.  I'd prefer to keep all tests into one framework if possible.  The probability of this need is probably pretty low though

### LOE
Tough to put any specific numbers on LOE since I haven't done this before and not sure I follow all the steps and integration points, so I'll just say I think this would, personally, take me longer to do than option 2.

## Option 2 - RSpec/Capybara/Selenium setup
Based on some research I've been doing, I've seen a couple setups using [RSpec](http://rspec.info/), [Capybara](https://github.com/teamcapybara/capybara), and Selenium to do these tests.  Following something like [this](https://gist.github.com/deanmarano/aeae5cd2d357fec1b06e30ead397d4e3) makes it look pretty easy to setup and configure.  

### Pros
- I think this solution matches the underlying technology better and will be easier to extend if ever required.
- Personally, I think this is a more streamlined and easier setup
- Actual e2e tests are written in Selenium WebDriver so familiarity for tests should not be an issue

### Cons
- If the number of tests grew significantly, executing them all may take longer (not sure, just my hunch)
- Lack of consistent implementations with owner's other projects

**Comment by mtlynch** [comment]
I'd like to do the Docker route. The core technology in both solutions is really Selenium. Everything else is just the layers around Selenium to kick off scripts and run them. Between the two, I'm much more familiar with Docker + Python than RSpec + Capybara + Ruby.

But jumping immediately to selenium + Docker is a big jump, so I propose we start by just building with a Docker container:

https://github.com/mtlynch/mtlynch.io/issues/221

**Comment by mtlynch** [comment]
I've been doing a lot of work with Docker lately, so I want to rethink strategy based on what I know now. Closing for now.
