### ISSUE TITLE
Enable strict_variables and strict_filters checks

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#257]
Looks like some new checks are available in 3.8.0:

https://jekyllrb.com/news/2018/04/19/jekyll-3-8-0-released/

This depends on #256.

**Comment by shredtechular** [comment]
Enabling `strict_variables` is not going to work with the parent theme or our image include solution.  It appears as though the use of `strict_variables` is that liquid will require the variables to exist in _all_ cases, in order to build. The build fails on optional values, even in cases where we check for them  using `{% if %}` syntax.  

The only way around this would be to specifically define every possible variable in each file and even then we may need to change template code for doing this.  I don't think this effort would be small and I also imagine you probably wouldn't like having to define every variable in each post and image?  So, I don't think I'd recommend this setting currently as there should be some way to declare optional parameters/default values into templates without flagging the `strict_variables` error.

We can enable `strict_filters` though without a problem.  Would you like to go ahead and just enable this individual check?

**Comment by mtlynch** [comment]
>We can enable strict_filters though without a problem. Would you like to go ahead and just enable this individual check?

Sure, that sounds good.

Thanks for the investigation and explanation.
